export const SOLANA_COINKICK_PROGRAMID = "8VjxHA3JZo7DyNoFWMKhW86XwuVQ4HWGME7WgSori7R8"; //devnet
export const FEE_ACCOUNT = "4cASLHHXtomyWCD6muAGeEF17dran74LnXx78LhVfwz3";
export const LIQUIDITY = "5KjtLUmuFenkLK8ZRsqcC2b7zoLaG1T4rGUeFgkqTGcL";